export const LAUNCHES_REQUEST = 'LAUNCHES_REQUEST'
export const LAUNCHES_SUCCESS = 'LAUNCHES_SUCCESS'
export const LAUNCHES_ERROR = 'LAUNCHES_ERROR'
export const LAUNCHES_LOADING = 'LAUNCHES_LOADING'
